#!/usr/bin/env bash

[ -d /sys/class/backlight/intel_backlight ] || exit

max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
act=$(cat /sys/class/backlight/intel_backlight/actual_brightness)

pct=$(echo "scale=0; (100 * $act) / $max" | bc)
if [ $pct -gt 100 ]; then
  echo "backlight: 100%"
else
  echo "backlight: $pct%"
fi
