#!/usr/bin/env bash

which baton &> /dev/null || exit

s=$(baton status)

if [ $? -ne 0 ] || [[ $s =~ "Couldn't" ]]; then
  echo "playing: none"
else
  track=$(echo "$s" | head -n1 | cut -d' ' -f2-)
  artist=$(echo "$s" | head -n2 | tail -n1 | cut -d ' ' -f2-)
  if [[ $s =~ "State: Paused" ]]; then
    p=" (p)"
  fi
  echo "playing: $artist - $track$p"
fi
