#!/usr/bin/env bash

which amixer &>/dev/null || exit

if which pulseaudio &> /dev/null; then
  d='-D pulse'
fi

get() {
  s=$(amixer $d get Master | grep 'Mono: Playback')

  if [[ $s =~ '[off]' ]]; then
    mut=" (m)"
  fi

  echo $s | sed -E "s/.*\[(.*)%\].*/volume: \1%$mut/"
}

change() {
  if [[ "$1" = "mute" ]]; then
    amixer $d set Master toggle
  else
    amixer $d set Master $1 unmute
  fi
}

[ -z "$1" ] && get || change "$@"
