behavior:
  volume_increment: 5
  liked_icon: "s "
  playing_icon: ""
  paused_icon: ""
  repeat_track_icon: ""
  repeat_context_icon: ""
  shuffle_icon: ""
keybindings:
  increase_volume: "="
  previous_track: "<"
  next_track: ">"
  seek_backwards: "("
  seek_forwards: ")"

